<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.2.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?> 
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>
<div class="blog-list" id="list-blog">
<?php
 foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postLeft span4">
            <div class="postDate">
            <?php 
				$date = strtotime($post->getCreatedTime());
				$date = date('d M Y', $date);				
			 ?>
             <span><?php echo $date; ?></span>
            </div>
            <div class="postImage">            
            	<img width="250" height="350" src="<?php echo $this->getUrl() ?>media/<?php echo $post->getPostImage(); ?>" alt="" />
            </div>
        </div>
        
        <div class="postRight span8">
        	<a class="postTitle" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <?php echo $this->getBookmarkHtml($post) ?>
        	<div class="postDetails">
            	<?php if($post->getUser()) {?>
            	<span class="icon-user"></span><?php //echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
                <?php } ?>
                <?php if(Mage::getBlockSingleton('blog/blog')->getTagsHtml($post)) {?>
                <span class="icon-tag"></span><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?>
                <?php } ?>
                              
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                <span class="icon-th-list"></span>
                    <?php //echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>               
                            <a href="<?php //echo $data['url']; ?>"><?php echo $data['title']; ?></a> 
                    <?php endforeach; ?> 
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?>
                <?php if ($this->getCommentsEnabled()): ?>
                <span class="icon-comments"></span>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php if($post->getCommentCount()==0) {?>Comment<?php }else {?>Comments <?php } ?></a> 
                <?php endif; ?>
            </div>
         </div>
    </div>
<?php endforeach; ?>
</div> 
<div id="blog-toolbar">
 <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
 </div>
 <?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php //$this->getPages(); ?>
